CREATE TABLE CUSTOMER(
     CUST_NUM DEC(3) Primary Key CHECK(CUST_NUM>=1 AND CUST_NUM<=100),
     CUST_NAME char(25) NOT NULL,
     CUST_FNAME char(20) NOT NULL,
     CUST_AREACODE char(3),
     AGENT_NUM char(3),
     FOREIGN KEY (AGENT_NUM) REFERENCES AGENT(AGT_NUM));

INSERT INTO CUSTOMER VALUES ('5','Andrews','Mark','416','5');
INSERT INTO CUSTOMER VALUES ('10','Chen','Terry','250','10');
INSERT INTO CUSTOMER VALUES ('15','Dasilva','Lila','416','15');
INSERT INTO CUSTOMER VALUES ('20','Edwards','George','416','20');
INSERT INTO CUSTOMER VALUES ('25','Eustace','Gina','519','25');

SELECT a.CUST_NUM, a.CUST_LNAME, a.CUST_FNAME, a.CUST_AREACODE, b.AGT_PHONE AS CUST_PHONE from CUSTOMER a, AGENT b where a.AGENT_NUM = b.AGT_NUM;
